name: omg

on:
  workflow_dispatch: 
jobs:
  build:
    name: Run

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:tomtomtom/yt-dlp
        sudo apt update
        sudo apt install yt-dlp
        sudo apt install ffmpeg
    - name: Create Firefox profile at fixed path
      run: |
        mkdir -p ${{ runner.temp }}/my_profile
        firefox -profile ${{ runner.temp }}/my_profile --headless &
        sleep 5
        pkill -f "firefox.*my_profile" || true
        echo "Cookie path: ${{ runner.temp }}/my_profile/cookies.sqlite"
    - name: Visit a site to generate cookies
      run: |
        firefox -profile /home/runner/work/_temp/my_profile --headless https://youtube.com &
        sleep 5
        pkill firefox || true
    - name: Convert cookies.sqlite to cookies.txt
      run: |
        sqlite3 -separator $'\t' /home/runner/work/_temp/my_profile/cookies.sqlite \
          "SELECT host, 
                  CASE WHEN host LIKE '.%' THEN 'TRUE' ELSE 'FALSE' END, 
                  path, 
                  CASE WHEN isSecure THEN 'TRUE' ELSE 'FALSE' END, 
                  expiry, 
                  name, 
                  value 
                  FROM moz_cookies;" > /home/runner/work/_temp/my_profile/cookies.txt
    - name: Download latest genshin jp video
      run: |
        yt-dlp \
        --playlist-items 1 \
        -o "%(channel)s/%(upload_date)s - %(title)s.%(ext)s" \
        --merge-output-format webm \
        --no-overwrites \
        -f "bestvideo[codec~=vp9][height<=720]+bestaudio[codec~=opus]/bestvideo[codec~=vp9][height<=720]+bestaudio/best" \
        --write-subs \
        --sub-lang en \
        --sub-format srt \
        --write-auto-subs \
        --cookies /home/runner/work/_temp/my_profile/cookies.txt \
        "https://www.youtube.com/@Genshin_JP"
