name: omg

on:
  workflow_dispatch: 
jobs:
  build:
    name: Run

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        sudo apt-get install -y ffmpeg
        pip install -q -U "yt-dlp[default]"

    - name: Fetch latest video URL from RSS feed
      id: fetch_video
      run: |
          # Use curl to get the RSS feed, extract the first entry's video link
          LATEST_URL=$(curl -s "https://inv.nadeko.net/feed/channel/UCAVR6Q0YgYa8xwz8rdg9Mrg" \
            | awk '/<entry>/{flag=1; next} flag && /<link rel="alternate" href="/{match($0, /href="([^"]*)"/, a); print a[1]; exit}')
          
          echo "Latest video URL: $LATEST_URL"
          echo "video_url=$LATEST_URL" >> $GITHUB_OUTPUT
    
    - name: Use the video URL
      run: |
          echo "The latest video is at: ${{ steps.fetch_video.outputs.video_url }}"
    - name: Filter extractors for Invidious
      run: |
          echo "Fetching yt-dlp extractors and filtering for 'invidious'..."
          RESULT=$(yt-dlp --list-extractors | grep -i invidious)
          echo "Result:"
          echo "$RESULT"
          if [ -z "$RESULT" ]; then
            echo "No Invidious-related extractors found."
          fi
    - name: Download latest genshin jp video
      run: |
        yt-dlp \
        --extractor-args 'invidious:instance=https://inv.nadeko.net;use_webpage=0' \
        -o "%(channel)s/%(upload_date)s - %(title)s.%(ext)s" \
        --merge-output-format webm \
        --no-overwrites \
        -f "bestvideo[codec~=vp9][height<=720]+bestaudio[codec~=opus]/bestvideo[codec~=vp9][height<=720]+bestaudio/best" \
        --write-subs \
        --sub-lang en \
        --sub-format srt \
        --write-auto-subs \
        "${{ steps.fetch_video.outputs.video_url }}"
